Initial pipeline
JetBrains-Research/docs-fine-tuning pull request #1
Opened 2021-11-11 12:26 UTC by Readrid

2021-11-12 14:03 UTC, egor-bogomolov requested changes
Thanks for making it! Here are some comments regarding the code and readability.

2021-11-12 14:03 UTC, egor-bogomolov commented on classification.py
> +    parser.add_argument("--topn", dest="topn", action="store", type=int, default=5)
Let's add `help=` in order to describe the meaning behind the keys.

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/util.py
> +    text = re.sub("\t", "", text)
For whitespace characters, maybe they should be replaced with spaces? In order to apply tokenization properly (otherwise words might glue together).

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/util.py
> +        return np.nan
Why not an empty list of None? Usage of `np.nan` looks suspicious here

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/preprocess_docs.py
> +    main(sys.argv[1:])
Let's stick to using argparse everywhere as it allows to use help messages, description, default values, errors, etc.

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/preprocess_docs.py
> +        with Path(f"data/docs/doc_{i}.txt").open(mode="w") as f:
Use `os.path.join` or `Path(..) / Path(..) / Path(..)` for joining paths as the current version won't work on Windows due to `/` vs `\`

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/preprocess_csv.py
> +    parser.add_argument("--test_size", dest="test_size", action="store", type=float, default=0.2)
Same about `help` messages

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/preprocess_csv.py
> +    return parser.parse_args(arguments)
You can call it without passing arguments explicitly here.

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/preprocess_csv.py
> +    )
Maybe it is easier to pick the needed columns rather than drop everything else? :)

2021-11-12 14:03 UTC, egor-bogomolov commented on data_processing/util.py
> +        return np.nan
Well, got it, you wanted to use `pd.dropna(..)` later. Dropping the `None`s is as easy but I would say it is easier to understand when reading

2021-11-12 14:03 UTC, egor-bogomolov commented on train_models.py
> +    tmp_file = get_tmpfile("pretrained_vectors.txt")
Consider passing it as an argument rather than using it from the global scope

2021-11-12 14:03 UTC, egor-bogomolov commented on train_models.py
> +    model.save("models/word2vec_pretrained.model")
Use `os.path.join` (as well as for other paths in this file)

2021-11-12 14:03 UTC, egor-bogomolov commented on train_models.py
> +def train_finetuned(train_corpus, vector_size, epochs, docs, init_vocab):
You have quite a lot of duplicated code over three functions. Maybe you can merge it into a single one where you pass the training pipeline.

2021-11-12 14:03 UTC, egor-bogomolov commented on classification.py
> +        result += model[word]
What happens for OOV words?

2021-11-12 14:03 UTC, egor-bogomolov commented on classification.py
> +    return np.linalg.norm(vec1 - vec2)
It is actually better to use cosine similarity with embeddings (dot product divided by vector norms).

2021-11-12 14:03 UTC, egor-bogomolov commented on classification.py
> +        TP += val
It is not recall as far as I understand. It would be better described as "success rate": you compute the ratio of examples where you get at least one right among top-K?

2021-11-12 20:19 UTC, Readrid commented on classification.py
> +    parser.add_argument("--topn", dest="topn", action="store", type=int, default=5)
Added

2021-11-12 20:23 UTC, Readrid commented on data_processing/util.py
> +    text = re.sub("\t", "", text)
Fixed

2021-11-12 20:27 UTC, Readrid commented on data_processing/util.py
> +        return np.nan
For now, I left it as it was for ease of implementation.

2021-11-12 20:28 UTC, Readrid commented on data_processing/preprocess_docs.py
> +    main(sys.argv[1:])
Added argparse to this file

2021-11-12 20:29 UTC, Readrid commented on data_processing/preprocess_docs.py
> +        with Path(f"data/docs/doc_{i}.txt").open(mode="w") as f:
Fixed

2021-11-12 20:29 UTC, Readrid commented on data_processing/preprocess_csv.py
> +    parser.add_argument("--test_size", dest="test_size", action="store", type=float, default=0.2)
Added

2021-11-12 20:30 UTC, Readrid commented on data_processing/preprocess_csv.py
> +    return parser.parse_args(arguments)
Honestly, I didn't quite understand what you mean here. Can you explain in more detail, please?

2021-11-12 20:35 UTC, Readrid commented on data_processing/preprocess_csv.py
> +    )
For another dataset, we don't have to drop the columns in this place. If we still need it, I'll be think about it )

2021-11-12 20:36 UTC, Readrid commented on train_models.py
> +    tmp_file = get_tmpfile("pretrained_vectors.txt")
Added tmp_file as an argument for the script

2021-11-12 20:36 UTC, Readrid commented on train_models.py
> +    model.save("models/word2vec_pretrained.model")
Fixed

2021-11-12 20:36 UTC, Readrid commented on train_models.py
> +def train_finetuned(train_corpus, vector_size, epochs, docs, init_vocab):
Fixed

2021-11-12 20:39 UTC, Readrid commented on classification.py
> +        result += model[word]
I call ```model.build_vocab(test_corpus, update=True)``` in ```get_recall```. Apparently this method initializes embeddings randomly for OOV words

2021-11-12 20:39 UTC, Readrid commented on classification.py
> +    return np.linalg.norm(vec1 - vec2)
Fixed

2021-11-12 20:46 UTC, Readrid commented on classification.py
> +        TP += val
Yes, but why isn't this a recall? We take only those vectors that are duplicates, count how many of them our model took as duplicates (thus we get TP), and then divide the TP by the total number of real duplicates. It seems to be by definition a recall...

2021-12-06 16:40 UTC, egor-bogomolov reviewed
Thanks for fixing! There are still some things to clarify (see comments).

2021-12-06 16:40 UTC, egor-bogomolov commented on classification.py
> +        result += model[word]
A better way would be to skip them (as we average the results afterward). If we ran a classifier, it would be nice to mark them as <UNK> and have a single embedding for all of them.

2021-12-06 16:40 UTC, egor-bogomolov commented on data_processing/preprocess_csv.py
> +    return parser.parse_args(arguments)
If you only call this method with `sys.argv[:1]`, just drop `arguments`, as it will automatically refer to `sys.argv` ([see here](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_args))

2021-12-06 16:40 UTC, egor-bogomolov commented on data_processing/util.py
> +        return np.nan
Please, add a comment here to clarify things.

2021-12-29 14:51 UTC, egor-bogomolov approved these changes
Thanks for fixes, LGTM now!

2022-01-10 07:13 UTC, merged